/**
 * @fileoverview Events Schema - Rich event types with automation support
 * Supports viewing, follow-up, contract, valuation, open_house, consultation, etc.
 */

import {
  pgTable,
  serial,
  integer,
  varchar,
  text,
  timestamp,
  boolean,
  jsonb,
  pgEnum,
  index,
  decimal,
  unique,
  check,
} from 'drizzle-orm/pg-core';
import type { InferSelectModel, InferInsertModel } from 'drizzle-orm';
import { users } from './users';
import { clients } from './clients';
import { properties } from './properties';

// =============================================================================
// Enums
// =============================================================================

export const eventTypeEnum = pgEnum('event_type', [
  'viewing',
  'follow_up',
  'contract_signing',
  'key_handover',
  'valuation',
  'open_house',
  'consultation',
  'inspection',
  'negotiation',
  'other',
]);

export const eventStatusEnum = pgEnum('event_status', [
  'draft',
  'scheduled',
  'confirmed',
  'in_progress',
  'completed',
  'cancelled',
  'no_show',
  'rescheduled',
]);

export const reminderStatusEnum = pgEnum('reminder_status', [
  'pending',
  'sent',
  'failed',
  'cancelled',
]);

export const reminderChannelEnum = pgEnum('reminder_channel', [
  'email',
  'sms',
  'push',
  'in_app',
]);

// =============================================================================
// Event Templates
// =============================================================================

export const eventTemplates = pgTable('event_templates', {
  id: serial('id').primaryKey(),
  name: varchar('name', { length: 100 }).notNull().unique(),
  eventType: eventTypeEnum('event_type').notNull(),
  description: text('description'),

  defaultDurationMinutes: integer('default_duration_minutes').notNull().default(60),
  defaultLocation: text('default_location'),
  defaultDescriptionTemplate: text('default_description_template'),

  // JSON schemas
  customFields: jsonb('custom_fields').default([]),
  reminderPresets: jsonb('reminder_presets').default([]),
  followUpRules: jsonb('follow_up_rules').default({}),
  suggestedNextSteps: jsonb('suggested_next_steps').default([]),

  color: varchar('color', { length: 7 }).default('#3B82F6'),
  icon: varchar('icon', { length: 50 }).default('calendar'),

  isActive: boolean('is_active').notNull().default(true),
  isSystem: boolean('is_system').notNull().default(false),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

// =============================================================================
// Events
// =============================================================================

export const events = pgTable(
  'events',
  {
    id: serial('id').primaryKey(),
    title: varchar('title', { length: 500 }).notNull(),
    eventType: eventTypeEnum('event_type').notNull().default('other'),
    status: eventStatusEnum('status').notNull().default('scheduled'),
    templateId: integer('template_id').references(() => eventTemplates.id, { onDelete: 'set null' }),

    startTime: timestamp('start_time', { withTimezone: true }).notNull(),
    endTime: timestamp('end_time', { withTimezone: true }).notNull(),
    allDay: boolean('all_day').notNull().default(false),
    timezone: varchar('timezone', { length: 50 }).default('Europe/Madrid'),

    location: text('location'),
    locationLat: decimal('location_lat', { precision: 10, scale: 8 }),
    locationLng: decimal('location_lng', { precision: 11, scale: 8 }),
    virtualMeetingUrl: text('virtual_meeting_url'),

    description: text('description'),
    internalNotes: text('internal_notes'),
    outcomeNotes: text('outcome_notes'),

    propertyId: integer('property_id').references(() => properties.id, { onDelete: 'set null' }),
    clientId: integer('client_id').references(() => clients.id, { onDelete: 'set null' }),
    agentId: integer('agent_id').references(() => users.id, { onDelete: 'set null' }).notNull(),

    metadata: jsonb('metadata').default({}),

    parentEventId: integer('parent_event_id'),  // Self-ref handled at DB level
    autoGenerated: boolean('auto_generated').notNull().default(false),

    googleEventId: varchar('google_event_id', { length: 255 }),
    googleCalendarId: varchar('google_calendar_id', { length: 255 }),

    completedAt: timestamp('completed_at', { withTimezone: true }),
    cancelledAt: timestamp('cancelled_at', { withTimezone: true }),
    cancellationReason: text('cancellation_reason'),

    createdBy: integer('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (table) => ({
    startTimeIdx: index('idx_events_start_time').on(table.startTime),
    statusIdx: index('idx_events_status').on(table.status),
    typeIdx: index('idx_events_type').on(table.eventType),
    agentIdx: index('idx_events_agent').on(table.agentId),
    clientIdx: index('idx_events_client').on(table.clientId),
    propertyIdx: index('idx_events_property').on(table.propertyId),
  })
);

// =============================================================================
// Event Attendees
// =============================================================================

export const eventAttendees = pgTable(
  'event_attendees',
  {
    id: serial('id').primaryKey(),
    eventId: integer('event_id').references(() => events.id, { onDelete: 'cascade' }).notNull(),
    clientId: integer('client_id').references(() => clients.id, { onDelete: 'set null' }),
    userId: integer('user_id').references(() => users.id, { onDelete: 'set null' }),
    name: varchar('name', { length: 255 }),
    email: varchar('email', { length: 255 }),
    phone: varchar('phone', { length: 50 }),
    rsvpStatus: varchar('rsvp_status', { length: 20 }).default('pending'),
    notifyEmail: boolean('notify_email').default(true),
    notifySms: boolean('notify_sms').default(false),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    eventIdx: index('idx_attendees_event').on(table.eventId),
    clientIdx: index('idx_attendees_client').on(table.clientId),
  })
);

// =============================================================================
// Event Reminders
// =============================================================================

export const eventReminders = pgTable(
  'event_reminders',
  {
    id: serial('id').primaryKey(),
    eventId: integer('event_id').references(() => events.id, { onDelete: 'cascade' }).notNull(),
    remindAt: timestamp('remind_at', { withTimezone: true }).notNull(),
    minutesBefore: integer('minutes_before').notNull(),
    channel: reminderChannelEnum('channel').notNull().default('email'),
    attendeeId: integer('attendee_id').references(() => eventAttendees.id, { onDelete: 'cascade' }),
    targetEmail: varchar('target_email', { length: 255 }),
    targetPhone: varchar('target_phone', { length: 50 }),
    targetUserId: integer('target_user_id').references(() => users.id, { onDelete: 'cascade' }),
    status: reminderStatusEnum('status').notNull().default('pending'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    errorMessage: text('error_message'),
    retryCount: integer('retry_count').default(0),
    subject: varchar('subject', { length: 500 }),
    body: text('body'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  },
  (table) => ({
    pendingIdx: index('idx_reminders_pending').on(table.remindAt, table.status),
    eventIdx: index('idx_reminders_event').on(table.eventId),
  })
);

// =============================================================================
// Event Analytics
// =============================================================================

export const eventAnalytics = pgTable('event_analytics', {
  id: serial('id').primaryKey(),
  eventId: integer('event_id').references(() => events.id, { onDelete: 'cascade' }).notNull().unique(),
  timeToCompleteMinutes: integer('time_to_complete_minutes'),
  prepTimeMinutes: integer('prep_time_minutes'),
  ledToOffer: boolean('led_to_offer').default(false),
  ledToContract: boolean('led_to_contract').default(false),
  conversionValue: decimal('conversion_value', { precision: 12, scale: 2 }),
  clientSatisfaction: integer('client_satisfaction'),
  clientFeedback: text('client_feedback'),
  followUpCreated: boolean('follow_up_created').default(false),
  followUpEventId: integer('follow_up_event_id').references(() => events.id, { onDelete: 'set null' }),
  daysToFollowUp: integer('days_to_follow_up'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

// =============================================================================
// Event Activity Log
// =============================================================================

export const eventActivityLog = pgTable(
  'event_activity_log',
  {
    id: serial('id').primaryKey(),
    eventId: integer('event_id').references(() => events.id, { onDelete: 'cascade' }).notNull(),
    action: varchar('action', { length: 50 }).notNull(),
    oldValue: jsonb('old_value'),
    newValue: jsonb('new_value'),
    performedBy: integer('performed_by').references(() => users.id, { onDelete: 'set null' }),
    performedAt: timestamp('performed_at', { withTimezone: true }).defaultNow(),
    notes: text('notes'),
  },
  (table) => ({
    eventIdx: index('idx_activity_event').on(table.eventId),
  })
);

// =============================================================================
// Types
// =============================================================================

export type EventTemplate = InferSelectModel<typeof eventTemplates>;
export type CreateEventTemplate = InferInsertModel<typeof eventTemplates>;

export type Event = InferSelectModel<typeof events>;
export type CreateEvent = InferInsertModel<typeof events>;
export type UpdateEvent = Partial<Omit<CreateEvent, 'id'>>;

export type EventAttendee = InferSelectModel<typeof eventAttendees>;
export type CreateEventAttendee = InferInsertModel<typeof eventAttendees>;

export type EventReminder = InferSelectModel<typeof eventReminders>;
export type CreateEventReminder = InferInsertModel<typeof eventReminders>;

export type EventAnalyticsRow = InferSelectModel<typeof eventAnalytics>;
export type EventActivityLogRow = InferSelectModel<typeof eventActivityLog>;

// =============================================================================
// Interfaces for automation
// =============================================================================

export interface ReminderPreset {
  channel: 'email' | 'sms' | 'push' | 'in_app';
  minutes_before: number;
}

export interface FollowUpRules {
  auto_create?: boolean;
  delay_hours?: number;
  follow_up_type?: string;
  template_name?: string;
}

export interface CustomField {
  key: string;
  label: string;
  type: 'text' | 'number' | 'boolean' | 'select' | 'date';
  options?: string[];
  min?: number;
  max?: number;
  required?: boolean;
}

export interface SuggestedNextStep {
  label: string;
  action?: string;
  auto?: boolean;
}
