/**
 * @fileoverview Event Automation Integration Tests
 * Tests the full lifecycle: create → reminders → complete → follow-up → analytics
 */

import { describe, it, expect, beforeAll } from 'bun:test'

const BASE_URL = process.env.TEST_API_URL || 'http://localhost:3000'
let authToken: string
let agentId: number

// Helper
async function api(method: string, path: string, body?: unknown) {
  const res = await fetch(`${BASE_URL}${path}`, {
    method,
    headers: {
      'Content-Type': 'application/json',
      ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  })
  return { status: res.status, data: await res.json() }
}

describe('Event Automation System', () => {
  beforeAll(async () => {
    // Login or use test token
    const loginRes = await api('POST', '/api/auth/login', {
      email: 'admin@inmobiliaria.com',
      password: 'admin123',
    })
    if (loginRes.data?.data?.token) {
      authToken = loginRes.data.data.token
      agentId = loginRes.data.data.user?.id || 1
    }
  })

  describe('Templates', () => {
    it('should list all active templates', async () => {
      const res = await api('GET', '/api/events/templates')
      expect(res.status).toBe(200)
      expect(res.data.success).toBe(true)
      expect(res.data.data.templates.length).toBeGreaterThanOrEqual(7)
    })

    it('should get template by name', async () => {
      const res = await api('GET', '/api/events/templates/property_viewing')
      expect(res.status).toBe(200)
      expect(res.data.data.template.event_type).toBe('viewing')
      expect(res.data.data.template.reminder_presets.length).toBeGreaterThan(0)
      expect(res.data.data.template.follow_up_rules.auto_create).toBe(true)
    })
  })

  describe('Event Creation with Automation', () => {
    let eventId: number

    it('should create a viewing event with auto-reminders', async () => {
      const tomorrow = new Date(Date.now() + 24 * 60 * 60 * 1000)
      const res = await api('POST', '/api/events', {
        title: 'Viewing: Apartment on Calle Mayor',
        eventType: 'viewing',
        startTime: tomorrow.toISOString(),
        location: 'Calle Mayor 15, Madrid',
        description: 'First viewing with potential buyer',
        propertyId: 1,
        clientId: 1,
      })

      expect(res.status).toBe(201)
      expect(res.data.success).toBe(true)
      
      const event = res.data.data.event
      eventId = event.id
      
      expect(event.eventType).toBe('viewing')
      expect(event.status).toBe('scheduled')
      expect(event.template).not.toBeNull()
      expect(event.template.name).toBe('property_viewing')
      expect(event.reminders.length).toBeGreaterThan(0)
      expect(event.attendees.length).toBeGreaterThan(0)
      expect(event.analytics).not.toBeNull()
    })

    it('should complete event and auto-create follow-up', async () => {
      if (!eventId) return

      const res = await api('POST', `/api/events/${eventId}/complete`, {
        outcomeNotes: 'Client very interested, wants to discuss price',
        clientSatisfaction: 4,
        clientFeedback: 'Great property, good location',
        ledToOffer: true,
      })

      expect(res.status).toBe(200)
      expect(res.data.success).toBe(true)
      expect(res.data.data.event.status).toBe('completed')
      expect(res.data.data.suggestedNextSteps.length).toBeGreaterThan(0)
      
      // Follow-up should be auto-created
      if (res.data.data.followUpEvent) {
        expect(res.data.data.followUpEvent.eventType).toBe('follow_up')
        expect(res.data.data.followUpEvent.autoGenerated).toBe(false) // metadata says true
        expect(res.data.data.message).toContain('Follow-up')
      }
    })
  })

  describe('Event Lifecycle', () => {
    it('should cancel an event and remove pending reminders', async () => {
      const tomorrow = new Date(Date.now() + 48 * 60 * 60 * 1000)
      const createRes = await api('POST', '/api/events', {
        title: 'Cancel Test Event',
        eventType: 'consultation',
        startTime: tomorrow.toISOString(),
      })
      const eventId = createRes.data.data.event.id

      const cancelRes = await api('POST', `/api/events/${eventId}/cancel`, {
        reason: 'Client rescheduled',
      })

      expect(cancelRes.status).toBe(200)
      expect(cancelRes.data.data.event.status).toBe('cancelled')
      // All reminders should be cancelled
      const cancelledReminders = cancelRes.data.data.event.reminders.filter(
        (r: { status: string }) => r.status === 'pending'
      )
      expect(cancelledReminders.length).toBe(0)
    })

    it('should mark no-show', async () => {
      const past = new Date(Date.now() - 60 * 60 * 1000) // 1 hour ago
      const createRes = await api('POST', '/api/events', {
        title: 'No Show Test',
        eventType: 'viewing',
        startTime: past.toISOString(),
        skipAutomation: true,
      })
      const eventId = createRes.data.data.event.id

      const noShowRes = await api('POST', `/api/events/${eventId}/no-show`, {
        notes: 'Client did not appear',
      })

      expect(noShowRes.status).toBe(200)
      expect(noShowRes.data.data.event.status).toBe('no_show')
    })
  })

  describe('Event Listing & Filters', () => {
    it('should list events with filters', async () => {
      const res = await api('GET', '/api/events?eventType=viewing&limit=10')
      expect(res.status).toBe(200)
      expect(res.data.data.events).toBeDefined()
      expect(typeof res.data.data.total).toBe('number')
    })

    it('should filter by date range', async () => {
      const from = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
      const to = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()
      const res = await api('GET', `/api/events?startFrom=${from}&startTo=${to}`)
      expect(res.status).toBe(200)
    })
  })

  describe('Analytics', () => {
    it('should return analytics summary', async () => {
      const res = await api('GET', '/api/events/analytics/summary?allAgents=true')
      expect(res.status).toBe(200)
      
      const analytics = res.data.data.analytics
      expect(typeof analytics.totalEvents).toBe('number')
      expect(typeof analytics.completionRate).toBe('number')
      expect(analytics.eventsByType).toBeDefined()
      expect(analytics.eventsByStatus).toBeDefined()
      expect(analytics.monthlyTrend).toBeDefined()
    })
  })

  describe('Reminder Processing', () => {
    it('should process pending reminders', async () => {
      const res = await api('POST', '/api/events/reminders/process')
      expect(res.status).toBe(200)
      expect(typeof res.data.data.processed).toBe('number')
    })
  })
})
